apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-app-config
data:
  config.yaml: |
    bitbank_host: https://public.bitbank.cc
    mysql_host: trade-mysql7
    mysql_port: 3306
    mysql_database: trade
    app_port: 80
    app_domain: localhost