apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: orensimple/trade-core-app:latest
    context: orensimple/trade-core-app:latest
deploy:
  kubectl:
    manifests:
    - configmap.yaml
    - secret.yaml
    - initdb.yaml
    - deployment.yaml
    - service.yaml
    - ingress.yaml
