apiVersion: v1
kind: Service
metadata:
  name: {{ include "trade-order.fullname" . }}
  labels:
    {{- include "trade-order.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: web
  selector:
    {{- include "trade-order.selectorLabels" . | nindent 4 }}