apiVersion: apps/v1
kind: Deployment
metadata:
    name: trade-app
spec:
    replicas: 2
    selector:
       matchLabels:
          app: trade-app
    template:
       metadata:
          labels:
             app: trade-app
       spec:
          containers:
          - name: trade-app
            image: orensimple/trade-core-app:latest
            imagePullPolicy: "Always"
            ports:
              - name: web 
                containerPort: 8080
            env:
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: trade-db-secret
                    key: db_user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: trade-db-secret
                    key: db_password
            volumeMounts:
              - name: trade-app-config
                mountPath: "/config/config.yaml"
                subPath: "config.yaml"
                readOnly: true
          volumes:
            - name: trade-app-config
              configMap: 
                name: trade-app-config
                items:
                - key: "config.yaml"
                  path: "config.yaml"
