apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trade-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: rewrite
  namespace: default
spec:
  rules:
  -  host: "arch.homework"
     http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: trade-service
            servicePort: 80