apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trade-app
  labels:
    app: trade-app
spec:
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: trade-app
  endpoints:
  - port: web
    interval: 10s