apiVersion: v1
kind: Service
metadata:
  name: trade-app
  labels:
    app: trade-app
spec:
  selector:
    app: trade-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
  type: NodePort
