apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trade-deployment
spec:
  jobLabel: trade-deployment
  selector:
    matchLabels:
      app: trade-service
  endpoints:
  - interval: 15s
    port: web
    path: /metrics
