replicaCount: 1

image:
  repository: orensimple/trade-order-app
  tag: latest

service:
  type: NodePort
  port: 80

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  
ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/"]
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
