apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trade-billing-chart.fullname" . }}
  labels:
    {{- include "trade-billing-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trade-billing-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trade-billing-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: trade-db-secret
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trade-db-secret
                  key: db_password
          volumeMounts:
            - name: trade-billing-config
              mountPath: "/config/config.yaml"
              subPath: "config.yaml"
              readOnly: true
      volumes:
        - name: trade-billing-config
          configMap: 
            name: trade-billing-config
            items:
            - key: "config.yaml"
              path: "config.yaml"