apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: mysql:latest
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: trade-db-secret
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trade-db-secret
                  key: db_password
          command:
           - sh
           - "-c"
           - |
           - "until mysql --host=trade-mysql7-primary --user={MYSQL_USER} --password={MYSQL_PASSWORD} --execute=\"SELECT 1;\"; do echo waiting for mysql; sleep 2; done;" 
      containers:
      - name: post-install-job
        image: mysql:latest
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: trade-db-secret
                key: db_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: trade-db-secret
                key: db_password
        command:
          - sh
          - "-c"
          - |
            mysql --host=trade-mysql7-primary --user=$MYSQL_USER --password=$MYSQL_PASSWORD <<'EOF'
              use trade;
              create table users
              (
                  id         varchar(36)                         not null,
                  email      varchar(64)                         not null,
                  password   varchar(64)                         not null,
                  phone      varchar(20)                         null,
                  first_name varchar(32)                         not null,
                  last_name  varchar(32)                         not null,
                  passport   int                                 null comment 'series and number in the format 5612453765',
                  male       tinyint(1)                          null comment 'man is true, a woman is false, not selected null',
                  address    varchar(256)                        null,
                  about      varchar(256)                        null comment 'additional information',
                  created_at timestamp default CURRENT_TIMESTAMP not null,
                  updated_at timestamp                           null,
                  constraint users_id_uindex
                      unique (id)
              )
                  comment 'User data table';
              create index user_email_idx
                  on users (email);
              create index user_first_name_last_name_ftsidx
                  on users (last_name, first_name);
              alter table users
                  add primary key (id);
              insert into trade.users (id, email, password, phone, first_name, last_name, passport, male, address, about, created_at, updated_at)  values ('f3bf75a9-ea4c-4f57-9161-cfa8f96e2d0b', 'admin@mail.ru', '$2a$04$Q65Ug0F8llqw4DOPZ13gu.iWR7pDu7zwEdg9SxElmdUQoKnpD2CGe', '+79228862029',  'Ivan', 'Ivanov', 324, 1, 'afs', '', '2021-11-17 07:23:19', null);
              create table accounts
              (
                  id            varchar(36)  not null,
                  user_id       varchar(36)  not null,
                  account_id    varchar(36)  not null,
                  currency_code varchar(256) null,
                  primary key (user_id, account_id),
                  constraint user_accounts_id_uindex
                  unique (id),
                  constraint user_accounts_users_id_fk
                  foreign key (user_id) references users (id)
              );
              create index user_accounts_accounts_id_fk
              on accounts (account_id);
            EOF

  backoffLimit: 0
